function results = ShowStatus(Params)
global randNum;
temp = [strcat('RA:',string(Params.RA),' DEC:',string(Params.DEC), ' ROT:',string(Params.ROT), '(deg)    MagLimit:',string(Params.Mag), ...
    '    FoVxy:',string(Params.FoVx),'x',string(Params.FoVy),'(deg)    PixelNum_XY:',string(Params.PixelNum_X), 'x',string(Params.PixelNum_Y),...
    ' '),strcat('BlurInfo//','  Sigma:',string(Params.sigma),'  K1, K2, K3:', string(Params.K1),', ',string(Params.K2),', ',string(Params.K3)),...
    strcat('BackNoise: ',string(Params.MinNoise),'~',string(Params.MaxNoise),'(uint8) ',...
    '  Missing Stars#:',string(randNum),'  RandomObject#:')];

results = cellstr(temp);
end